name: Release Package
on:
  release:
    types:
      - "created"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["16.x"]

    steps:
      - name: Checkout Package Codes
        uses: actions/checkout@v2

      - name: Install Node JS ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          registry-url: 'https://registry.npmjs.org/'
          scope: "@kairosafrika"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install Package Deps.
        run: yarn install --frozon-lockfile

      - name: Linting & Formatting
        run: yarn run lint && yarn run format

      - name: Running Tests
        run: yarn run test

      - name: Publish Package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
#
#      - name: Semantic Release
#        if: github.event_name == 'push' && matrix.node-version == '14.x'
#        uses: cycjimmy/semantic-release-action@v2
#        env:
#          GH_TOKEN: ${{ secrets.GH_TOKEN }}
#          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}